version: "2"

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    pre_build:
      - pip install --upgrade pip
      - pip install . --group doc

python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
