from __future__ import annotations

from abc import ABC, abstractmethod
from typing import TYPE_CHECKING, TextIO

if TYPE_CHECKING:
    from gamspy import Model, Options


class ExecutionEngine(ABC):
    """Runs the GAMS code generated by a Container on the local machine."""

    @property
    @abstractmethod
    def is_running(self) -> bool:
        """Whether the engine is ready to execute jobs."""

    @abstractmethod
    def start(self) -> None:
        """Starts the engine."""

    @abstractmethod
    def execute(
        self,
        gams_code: str,
        options: Options,
        job_name: str,
        model: Model | None,
        output: TextIO | None,
    ) -> None:
        """
        Executes the given GAMS code.

        Raises
        ------
        GamspyException
            If GAMS reports an error while executing the code.
        """

    @abstractmethod
    def interrupt(self) -> None:
        """Interrupts the running job."""

    @abstractmethod
    def stop(self) -> None:
        """Stops the engine. Must be safe to call more than once."""
