from __future__ import annotations

import itertools
from collections import UserDict
from enum import Enum
from typing import Any

from gams.core.gdx import (
    GMS_EQUTYPE_B,
    GMS_EQUTYPE_E,
    GMS_EQUTYPE_G,
    GMS_EQUTYPE_L,
    GMS_EQUTYPE_N,
    GMS_EQUTYPE_X,
    GMS_MAX_INDEX_DIM,
    GMS_SSSIZE,
    GMS_UEL_IDENT_SIZE,
    GMS_VARTYPE_BINARY,
    GMS_VARTYPE_FREE,
    GMS_VARTYPE_INTEGER,
    GMS_VARTYPE_NEGATIVE,
    GMS_VARTYPE_POSITIVE,
    GMS_VARTYPE_SEMICONT,
    GMS_VARTYPE_SEMIINT,
    GMS_VARTYPE_SOS1,
    GMS_VARTYPE_SOS2,
)

GAMS_SYMBOL_MAX_LENGTH = GMS_UEL_IDENT_SIZE - 1
GAMS_UEL_MAX_LENGTH = GMS_UEL_IDENT_SIZE - 1
GAMS_DESCRIPTION_MAX_LENGTH = GMS_SSSIZE - 1
GAMS_MAX_INDEX_DIM = GMS_MAX_INDEX_DIM


class CasePreservingDict(UserDict):
    def __init__(self, *args, **kwargs):
        self._casefolded_key_map = {}
        super().__init__(*args, **kwargs)

    def __contains__(self, key):
        return key.casefold() in self._casefolded_key_map

    def __delitem__(self, key):
        del self.data[self._casefolded_key_map[key.casefold()]]
        del self._casefolded_key_map[key.casefold()]

    def __setitem__(self, key, item):
        key_cf = key.casefold()

        if key_cf not in self._casefolded_key_map:
            self.data[key] = item
            self._casefolded_key_map[key_cf] = key
        else:
            self.data[self._casefolded_key_map[key_cf]] = item

    def _repr_pretty_(self, p, cycle):
        if cycle:
            p.pretty(self.data)
        else:
            p.pretty(self.data)

    def __getitem__(self, key):
        return self.data[self._casefolded_key_map[key.casefold()]]

    def pop(self, key: str) -> Any:
        a = self.data.pop(self._casefolded_key_map[key.casefold()])
        del self._casefolded_key_map[key.casefold()]
        return a

    def get(self, key: str, default: Any | None = None) -> Any:
        try:
            return self.data.get(self._casefolded_key_map[key.casefold()])
        except KeyError:
            return default

    def copy(self) -> CasePreservingDict:
        import copy

        return copy.deepcopy(self)

    def setdefault(self, key: str, default: Any) -> Any:
        key_cf = key.casefold()
        if key_cf not in self._casefolded_key_map:
            self.__setitem__(key, default)
            return default
        else:
            return self.data[self._casefolded_key_map[key_cf]]

    def popitem(self) -> tuple:
        return self.data.popitem()

    def items(self):
        return self.data.items()

    def keys(self):
        return self.data.keys()

    def values(self):
        return self.data.values()


class DomainStatus(Enum):
    UNKNOWN = 0
    none = 1
    relaxed = 2
    regular = 3


GAMS_VARIABLE_SUBTYPES: dict[int, str] = {
    GMS_VARTYPE_BINARY: "binary",
    GMS_VARTYPE_INTEGER: "integer",
    GMS_VARTYPE_POSITIVE: "positive",
    GMS_VARTYPE_NEGATIVE: "negative",
    GMS_VARTYPE_FREE: "free",
    GMS_VARTYPE_SOS1: "sos1",
    GMS_VARTYPE_SOS2: "sos2",
    GMS_VARTYPE_SEMICONT: "semicont",
    GMS_VARTYPE_SEMIINT: "semiint",
}

TRANSFER_TO_GAMS_VARIABLE_SUBTYPES = {v: k for k, v in GAMS_VARIABLE_SUBTYPES.items()}

GAMS_EQUATION_SUBTYPES = {
    GMS_EQUTYPE_E: "eq",
    GMS_EQUTYPE_G: "geq",
    GMS_EQUTYPE_L: "leq",
    GMS_EQUTYPE_N: "nonbinding",
    GMS_EQUTYPE_X: "external",
    GMS_EQUTYPE_B: "boolean",
}

TRANSFER_TO_GAMS_EQUATION_SUBTYPES = {v: k for k, v in GAMS_EQUATION_SUBTYPES.items()}


EQU_TYPE = {
    "eq": "eq",
    "geq": "geq",
    "leq": "leq",
    "nonbinding": "nonbinding",
    "external": "external",
    "boolean": "boolean",
    "=e=": "eq",
    "e": "eq",
    "=g=": "geq",
    "g": "geq",
    "=l=": "leq",
    "l": "leq",
    "=n=": "nonbinding",
    "n": "nonbinding",
    "=x=": "external",
    "x": "external",
    "=b=": "boolean",
    "b": "boolean",
}


# equivalents
EPS = set(map("".join, itertools.product(*zip("EPS", "eps", strict=True))))
UNDEF = set(
    list(map("".join, itertools.product(*zip("UNDEF", "undef", strict=True))))
    + list(map("".join, itertools.product(*zip("UNDF", "undf", strict=True))))
)
NA = set(map("".join, itertools.product(*zip("NA", "na", strict=True))))

# Autogenerated symbol prefix for model attributes
ATTR_PREFIX = "autogenerated_"

# GAMS name -> GAMSPy name
MODEL_ATTRIBUTE_MAP = {
    "domUsd": "_num_domain_violations",
    "etAlg": "_algorithm_time",
    "etSolve": "_total_solve_time",
    "etSolver": "_total_solver_time",
    "iterUsd": "_num_iterations",
    "marginals": "_marginals",
    "maxInfes": "_max_infeasibility",
    "meanInfes": "_mean_infeasibility",
    "modelStat": "_status",
    "nodUsd": "_num_nodes_used",
    "number": "_solve_number",
    "numDepnd": "_num_dependencies",
    "numDVar": "_num_discrete_variables",
    "numEqu": "_num_equations",
    "numInfes": "_num_infeasibilities",
    "numNLIns": "_num_nonlinear_insts",
    "numNLNZ": "_num_nonlinear_zeros",
    "numNOpt": "_num_nonoptimalities",
    "numNZ": "_num_nonzeros",
    "numRedef": "_num_mcp_redefinitions",
    "numVar": "_num_variables",
    "numVarProj": "_num_bound_projections",
    "objEst": "_objective_estimation",
    "objVal": "_objective_value",
    "procUsed": "_used_model_type",
    "resGen": "_model_generation_time",
    "resUsd": "_solve_model_time",
    "solveStat": "_solve_status",
    "sumInfes": "_sum_infeasibilities",
    "sysVer": "_solver_version",
}
