leg-cli-3.13:
  stage: cli
  tags: [linux]
  image: python:3.13
  script:
    - python -m pip install uv && uv venv venv313 && source venv313/bin/activate && uv pip install pip
    - uv pip install .[dev,test] --force-reinstall
    - pytest -x -v -s -m 'cli' tests
  artifacts:
    name: linux_3.13
    expire_in: 2 hours
    paths: [dist/*]

leg-cli-3.9:
  stage: cli
  tags: [linux]
  image: python:3.9
  script:
    - python -m pip install uv && uv venv venv39 && source venv39/bin/activate && uv pip install pip
    - uv pip install .[dev,test] --force-reinstall
    - pytest -x -v -s -m 'cli' tests

dac-cli-3.13:
  stage: cli
  when: on_success
  tags: [macos-arm64]
  script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh && source $HOME/.local/bin/env
    - uv venv "gamspy-env-3.13${CI_COMMIT_SHORT_SHA}" --python 3.13
    - source "gamspy-env-3.13${CI_COMMIT_SHORT_SHA}"/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - pytest -x -v -s -m 'cli' tests
  artifacts:
    name: macos_arm64_3.13
    expire_in: 2 hours
    paths: [dist/*]

dac-cli-3.9:
  stage: cli
  needs: [dac-cli-3.13]
  tags: [macos-arm64]
  script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh && source $HOME/.local/bin/env
    - uv venv "gamspy-env-3.9${CI_COMMIT_SHORT_SHA}" --python 3.9
    - source "gamspy-env-3.9${CI_COMMIT_SHORT_SHA}"/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - pytest -x -v -s -m 'cli' tests

deg-cli-3.13:
  stage: cli
  tags: [macos]
  script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh && source $HOME/.local/bin/env
    - uv venv "gamspy-env-3.13${CI_COMMIT_SHORT_SHA}" --python 3.13
    - source "gamspy-env-3.13${CI_COMMIT_SHORT_SHA}"/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - pytest -x -v -s -m 'cli' tests
  artifacts:
    name: macos_x86_64_3.13
    expire_in: 2 hours
    paths: [dist/*]

deg-cli-3.9:
  stage: cli
  needs: [deg-cli-3.13]
  tags: [macos]
  script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh && source $HOME/.local/bin/env
    - uv venv "gamspy-env-3.9${CI_COMMIT_SHORT_SHA}" --python 3.9
    - source "gamspy-env-3.9${CI_COMMIT_SHORT_SHA}"/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - pytest -x -v -s -m 'cli' tests

wei-cli-3.13:
  stage: cli
  tags: [windows]
  image: winamd64/python:3.13
  script:
    - python --version
    - python -m pip install uv; uv venv .windows_venv313; .windows_venv313\Scripts\Activate; uv pip install pip
    - uv pip install .[dev,test] --force-reinstall
    - pytest -x -v -s -m 'cli' tests
  artifacts:
    name: windows_3.13
    expire_in: 2 hours
    paths: [dist/*]

wei-cli-3.9:
  stage: cli
  needs: [wei-cli-3.13]
  tags: [windows]
  image: winamd64/python:3.9
  script:
    - python --version
    - python -m pip install uv; uv venv .windows_venv39; .windows_venv39\Scripts\Activate; uv pip install pip
    - uv pip install .[dev,test] --force-reinstall
    - pytest -x -v -s -m 'cli' tests
