leg-cli-3.14:
  stage: cli
  needs: [setup-leg-toolchain]
  tags: [linux]
  image: debian:bookworm-slim
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - apt-get update && apt-get install -y ca-certificates git
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv venv314 --python 3.14
    - source venv314/bin/activate
    - uv pip install pip
    - uv build
    - uv pip install .[dev,test] --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests
  artifacts:
    name: linux_3.14
    expire_in: 2 hours
    paths: [dist/*]

leg-cli-3.10:
  stage: cli
  needs: [setup-leg-toolchain]
  tags: [linux]
  image: debian:bookworm-slim
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - apt-get update && apt-get install -y ca-certificates git
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv venv310 --python 3.10
    - source venv310/bin/activate
    - uv pip install pip
    - uv pip install .[dev,test] --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests

lag-cli-3.14:
  stage: cli
  needs: [setup-lag-toolchain]
  tags: [linux-arm64]
  image: debian:bookworm-slim
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - apt-get update && apt-get install -y ca-certificates git
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv venv314 --python 3.14
    - source venv314/bin/activate
    - uv pip install pip
    - uv build
    - uv pip install .[dev,test] --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests
  artifacts:
    name: linux_arm64_3.14
    expire_in: 2 hours
    paths: [dist/*]

lag-cli-3.10:
  stage: cli
  needs: [setup-lag-toolchain]
  tags: [linux-arm64]
  image: debian:bookworm-slim
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - apt-get update && apt-get install -y ca-certificates git
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv venv310 --python 3.10
    - source venv310/bin/activate
    - uv pip install pip
    - uv pip install .[dev,test] --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests

dac-cli-3.14:
  stage: cli
  when: on_success
  needs: [setup-dac-toolchain]
  tags: [macos-arm64]
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python 3.14
    - source .venv/bin/activate
    - uv build
    - uv pip install .[dev,test] pip --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests
  artifacts:
    name: macos_arm64_3.14
    expire_in: 2 hours
    paths: [dist/*]

dac-cli-3.10:
  stage: cli
  needs: [dac-cli-3.14, setup-dac-toolchain]
  tags: [macos-arm64]
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python 3.10
    - source .venv/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests

deg-cli-3.14:
  stage: cli
  needs: [setup-deg-toolchain]
  tags: [macos]
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python 3.14
    - source .venv/bin/activate
    - uv build
    - uv pip install .[dev,test] pip --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests
  artifacts:
    name: macos_x86_64_3.14
    expire_in: 2 hours
    paths: [dist/*]

deg-cli-3.10:
  stage: cli
  # Preserving dependency on 3.14 while adding toolchain
  needs: [deg-cli-3.14, setup-deg-toolchain]
  tags: [macos]
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python 3.10
    - source .venv/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests

wei-cli-3.14:
  stage: cli
  needs: [setup-wei-toolchain]
  tags: [windows]
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - $env:Path = "$CI_PROJECT_DIR\.uv_bin;$env:Path"
    - uv venv .venv --python 3.14
    - .venv\Scripts\Activate.ps1
    - uv pip install pip
    - uv build
    - uv pip install .[dev,test] --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests
  artifacts:
    name: windows_3.14
    expire_in: 2 hours
    paths: [dist/*]

wei-cli-3.10:
  stage: cli
  needs: [setup-wei-toolchain]
  tags: [windows]
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - $env:Path = "$CI_PROJECT_DIR\.uv_bin;$env:Path"
    - uv venv .venv --python 3.10
    - .venv\Scripts\Activate.ps1
    - uv pip install pip
    - uv pip install .[dev,test] --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests
