leg-cli-3.14:
  stage: cli
  tags: [hodori]
  image: python:3.14
  script:
    - python -m pip install uv && uv venv venv314 && source venv314/bin/activate && uv pip install pip && uv build
    - uv pip install .[dev,test] --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests
  artifacts:
    name: linux_3.14
    expire_in: 2 hours
    paths: [dist/*]

leg-cli-3.10:
  stage: cli
  tags: [hodori]
  image: python:3.10
  script:
    - python -m pip install uv && uv venv venv310 && source venv310/bin/activate && uv pip install pip
    - uv pip install .[dev,test] --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests

lag-cli-3.14:
  stage: cli
  tags: [linux-arm64]
  image: python:3.14
  script:
    - python -m pip install uv && uv venv venv314 && source venv314/bin/activate && uv pip install pip && uv build
    - uv pip install .[dev,test] --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests
  artifacts:
    name: linux_3.14
    expire_in: 2 hours
    paths: [dist/*]

lag-cli-3.10:
  stage: cli
  tags: [linux-arm64]
  image: python:3.10
  script:
    - python -m pip install uv && uv venv venv310 && source venv310/bin/activate && uv pip install pip
    - uv pip install .[dev,test] --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests

dac-cli-3.14:
  stage: cli
  when: on_success
  tags: [macos-arm64]
  script:
    - |
      if [ ! -f "${TMPDIR}uv" ]; then
        curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR=${TMPDIR} INSTALLER_NO_MODIFY_PATH=1 sh
      fi
<<<<<<< HEAD
    - ${TMPDIR}uv venv "${TMPDIR}gamspy-env-cli-3.14${CI_COMMIT_SHORT_SHA}" --python 3.14 && ${TMPDIR}uv build
=======
    - UV_PYTHON_BIN_DIR=${TMPDIR} ${TMPDIR}uv venv "${TMPDIR}gamspy-env-cli-3.14${CI_COMMIT_SHORT_SHA}" --python 3.14 && ${TMPDIR}uv build
>>>>>>> master
    - source "${TMPDIR}gamspy-env-cli-3.14${CI_COMMIT_SHORT_SHA}"/bin/activate
    - ${TMPDIR}uv pip install .[dev,test] pip --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests
  after_script:
    - rm -rf "${TMPDIR}gamspy-env-cli-3.14${CI_COMMIT_SHORT_SHA}"
  artifacts:
    name: macos_arm64_3.14
    expire_in: 2 hours
    paths: [dist/*]

dac-cli-3.10:
  stage: cli
  needs: [dac-cli-3.14]
  tags: [macos-arm64]
  script:
    - |
      if [ ! -f "${TMPDIR}/uv" ]; then
        curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR=${TMPDIR} INSTALLER_NO_MODIFY_PATH=1 sh
      fi
    - UV_PYTHON_BIN_DIR=${TMPDIR} ${TMPDIR}uv venv "${TMPDIR}gamspy-env-cli-3.10${CI_COMMIT_SHORT_SHA}" --python 3.10
    - source "${TMPDIR}gamspy-env-cli-3.10${CI_COMMIT_SHORT_SHA}"/bin/activate
    - ${TMPDIR}uv pip install .[dev,test] pip --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests
  after_script:
    - rm -rf "${TMPDIR}gamspy-env-cli-3.10${CI_COMMIT_SHORT_SHA}"

deg-cli-3.14:
  stage: cli
  tags: [macos]
  script:
    - |
      if [ ! -f "${TMPDIR}/uv" ]; then
        curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR=${TMPDIR} INSTALLER_NO_MODIFY_PATH=1 sh
      fi
    - UV_PYTHON_BIN_DIR=${TMPDIR} ${TMPDIR}uv venv "${TMPDIR}gamspy-env-cli-3.14${CI_COMMIT_SHORT_SHA}" --python 3.14 && ${TMPDIR}uv build
    - source "${TMPDIR}gamspy-env-cli-3.14${CI_COMMIT_SHORT_SHA}"/bin/activate
    - ${TMPDIR}uv pip install .[dev,test] pip --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests
  after_script:
    - rm -rf "${TMPDIR}gamspy-env-cli-3.14${CI_COMMIT_SHORT_SHA}"
  artifacts:
    name: macos_x86_64_3.14
    expire_in: 2 hours
    paths: [dist/*]

deg-cli-3.10:
  stage: cli
  needs: [deg-cli-3.14]
  tags: [macos]
  script:
    - |
      if [ ! -f "${TMPDIR}/uv" ]; then
        curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR=${TMPDIR} INSTALLER_NO_MODIFY_PATH=1 sh
      fi
    - UV_PYTHON_BIN_DIR=${TMPDIR} ${TMPDIR}uv venv "${TMPDIR}gamspy-env-cli-3.10${CI_COMMIT_SHORT_SHA}" --python 3.10
    - source "${TMPDIR}gamspy-env-cli-3.10${CI_COMMIT_SHORT_SHA}"/bin/activate
    - ${TMPDIR}uv pip install .[dev,test] pip --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests
  after_script:
    - rm -rf "${TMPDIR}gamspy-env-cli-3.10${CI_COMMIT_SHORT_SHA}"

wei-cli-3.14:
  stage: cli
  tags: [windows]
  image: winamd64/python:3.14
  script:
    - python --version
    - python -m pip install uv; uv venv .windows_venv314; .windows_venv314\Scripts\Activate; uv pip install pip; uv build
    - uv pip install .[dev,test] --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests
  artifacts:
    name: windows_3.14
    expire_in: 2 hours
    paths: [dist/*]

wei-cli-3.10:
  stage: cli
  tags: [windows]
  image: winamd64/python:3.10
  script:
    - python --version
    - python -m pip install uv; uv venv .windows_venv310; .windows_venv310\Scripts\Activate; uv pip install pip
    - uv pip install .[dev,test] --force-reinstall
    - python -m pytest -x -v -s -m 'cli' tests
