leg-build-docs:
  stage: docs
  when: manual
  needs: []
  allow_failure: true
  tags: [linux]
  image: ghcr.io/astral-sh/uv:python3.13-trixie-slim
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends make pandoc
  script:
    - uv venv .venv && source .venv/bin/activate
    - uv sync --group test --group doc && uv pip install pip
    - pytest --nbmake docs/user/notebooks/*.ipynb
    - ipython kernel install --name "python3" --user
    - cd docs && make linkcheck && make html
