leg-build-docs:
  stage: docs
  when: on_success
  tags: [linux]
  image: python:3.10
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install wheel build
    - python scripts/reinstall.py
    - pip install .[doc]
    - pytest --nbmake docs/user/notebooks/*.ipynb
    - ipython kernel install --name "python3" --user
    - wget https://github.com/jgm/pandoc/releases/download/3.1.8/pandoc-3.1.8-linux-amd64.tar.gz && tar xvzf pandoc-3.1.8-linux-amd64.tar.gz --strip-components 1
    - PATH=$(pwd)/bin/:$PATH
    - cd docs && make linkcheck && make html
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_COMMIT_BRANCH != "develop"
      when: never
    - when: on_success
