upload-wheel:
  stage: upload
  when: on_success
  tags: [linux]
  image: python:3.8
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install wheel build twine pip-audit
    - pip-audit -v
    - if [ "$?" == "0" ]; then echo "Audit passed!"; else exit 1; fi
    - twine upload dist/* -u $PF_PYPI_USERNAME -p $PF_PYPI_PASSWORD
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
      when: never
    - when: manual
