test-leg-3.11:
  stage: test
  when: on_success
  tags: [linux]
  image: python:3.11
  script:
    - pip install virtualenv
    - virtualenv venv311
    - source venv311/bin/activate
    - pip install wheel build
    - python scripts/reinstall.py
    - gamspy install solver mpsge
    - if [ "$CI_COMMIT_BRANCH" == "server-mode" ]; then gamspy install license $LOCAL_LICENSE; fi
    - coverage run --source=gamspy tests/test_gamspy.py --integration --doc --engine --model-library
    - if [ "$?" == "0" ]; then echo "All tests passed!"; else exit 1; fi
    - coverage report -m --data-file=".coverage"
    - coverage xml --data-file=".coverage"

  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    name: linux_3.11
    expire_in: 2 hours
    paths: [dist/*]
  coverage: '/TOTAL.*\s+(\d+\%)/'
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
      when: never
    - when: on_success



test-deg-3.11:
  stage: test
  tags: [macos]
  script:
    - eval "$($MINICONDA shell.bash hook)"
    - ulimit -n 10240
    - python scripts/atomic_conda_create.py "gamspy-env-3.11${CI_COMMIT_SHORT_SHA}" python=3.11
    - conda activate "$(pwd)/gamspy-env-3.11${CI_COMMIT_SHORT_SHA}"
    - conda install -c anaconda freetds
    - pip install wheel build
    - python scripts/reinstall.py
    - gamspy install solver mpsge
    - if [ "$CI_COMMIT_BRANCH" == "server-mode" ]; then gamspy install license $LOCAL_LICENSE; fi
    - coverage run --source=gamspy tests/test_gamspy.py --integration --doc --engine --model-library
    - if [ "$?" == "0" ]; then echo "All tests passed!"; else exit 1; fi
    - coverage report -m --data-file=".coverage"
    - coverage xml --data-file=".coverage"
  artifacts:
    name: macos_x86_64_3.11
    expire_in: 2 hours
    paths: [dist/*]
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
      when: never
    - when: on_success

test-dac-3.11:
  stage: test
  tags: [macos-arm64]
  script:
    - eval "$($MINICONDA shell.bash hook)"
    - ulimit -n 10240
    - python scripts/atomic_conda_create.py "gamspy-env-3.11${CI_COMMIT_SHORT_SHA}" python=3.11
    - conda activate "$(pwd)/gamspy-env-3.11${CI_COMMIT_SHORT_SHA}"
    - conda install -c anaconda freetds
    - pip install wheel build
    - python scripts/reinstall.py
    - gamspy install solver mpsge
    - if [ "$CI_COMMIT_BRANCH" == "server-mode" ]; then gamspy install license $LOCAL_LICENSE; fi
    - coverage run --source=gamspy tests/test_gamspy.py --integration --doc --engine --model-library
    - if [ "$?" == "0" ]; then echo "All tests passed!"; else exit 1; fi
    - coverage report -m --data-file=".coverage"
    - coverage xml --data-file=".coverage"
  artifacts:
    name: macos_arm64_3.11
    expire_in: 2 hours
    paths: [dist/*]
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
      when: never
    - when: on_success

test-wei-3.11:
  stage: test
  tags: [windows]
  image:
    name: $MACHINES_CONTAINER_REG/wei/builder-full:latest
    entrypoint: [""]
  script:
    - conda create -y -n gamspy-env-3.11 python=3.11
    - conda env list
    - conda activate gamspy-env-3.11
    - $env:Path = "C:\Miniconda\envs\gamspy-env-3.11;C:\Miniconda\envs\gamspy-env-3.11\Scripts;" + $env:Path
    - python --version
    - python -m pip install wheel build
    - python scripts/reinstall.py
    - gamspy install solver mpsge
    - if [ "$CI_COMMIT_BRANCH" == "server-mode" ]; then gamspy install license $LOCAL_LICENSE; fi
    - coverage run --source=gamspy tests\test_gamspy.py --integration --doc --engine --model-library
    - coverage report -m --data-file=".coverage"
    - coverage xml --data-file=".coverage"
  artifacts:
    name: windows_3.11
    expire_in: 2 hours
    paths: [dist/*]
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
      when: never
    - when: on_success
