update-website:
  stage: website
  needs: []
  tags: [linux]
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-full:latest
    entrypoint: [""]
  before_script:
    - git config --global user.email "puma@noreply.gams.com"
    - git config --global user.name "Gitlab Runner (puma)"
  script:
    - git clone https://engine_ci:${PF_GITLAB_WEBSITE_TOKEN}@git.gams.com/smann/new.gams.com.git --branch master --single-branch website
    - export GAMSPY_VERSION=$(grep "version" pyproject.toml -m 1 | cut -d "=" -f2)
    - export GAMSPY_RELEASE_DATE=\"$(date --rfc-3339=date)\"
    - cd website && sed -i -e 's/^gamspy_release*$/gamspy_release = '"${GAMSPY_VERSION}"'/' ./config.toml && sed -i -e 's/^\( *gamspy_release_date *= *\).*/\1'"${GAMSPY_RELEASE_DATE}"'/' ./config.toml && git add config.toml && git commit -m "Update gamspy version" && git push origin master
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
      when: never
    - when: manual
