run_formatter:
  stage: formatter
  needs: [install-gamsdist-leg]
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-full:latest
    entrypoint: [""]
  script:
    - yum install -y wget
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - sh Miniconda3-latest-Linux-x86_64.sh -b -p anaconda3
    - source anaconda3/bin/activate
    - conda create -y -n transfer-env python=3.8
    - conda activate transfer-env
    - source $(pwd)/anaconda3/bin/activate
    - conda activate transfer-env
    - pip install black
    - black src/gamspy --line-length=79 --preview --check
    - black tests --line-length=79 --preview --check
    - if [ "$?" == "0" ]; then echo "Formatter passed!"; else exit 1; fi
