run_formatter:
  stage: formatter
  when: on_success
  tags: [linux]
  image: python:3.8
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install black==23.12.1 pylint==3.0.3
    - pylint --fail-under=8 src/gamspy
    - black src/gamspy --line-length=79 --preview --check
    - if [ "$?" == "0" ]; then echo "Formatter passed!"; else exit 1; fi
    - black tests --line-length=79 --preview --check
    - if [ "$?" == "0" ]; then echo "Formatter passed!"; else exit 1; fi
