run_formatter:
  stage: formatter
  when: on_success
  tags: [linux]
  image:
    name: $MACHINES_CONTAINER_REG/leg/builder-full:latest
    entrypoint: [""]
  script:
    - curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o Miniconda3-latest-Linux-x86_64.sh
    - sh Miniconda3-latest-Linux-x86_64.sh -b -p anaconda3
    - source anaconda3/bin/activate
    - conda create -y -n transfer-env python=3.8
    - conda activate transfer-env
    - pip install black==23.12.1
    - black src/gamspy --line-length=79 --preview --check
    - if [ "$?" == "0" ]; then echo "Formatter passed!"; else exit 1; fi
    - black tests --line-length=79 --preview --check
    - if [ "$?" == "0" ]; then echo "Formatter passed!"; else exit 1; fi
