leg-performance:
  stage: performance
  needs: []
  tags: [puma]
  image: python:3.12
  when: manual
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install wheel build psutil
    - python scripts/reinstall.py
    - echo $GAMS_LICENSE > $(gamspy show base)/gamslice.txt
    - gamspy install license $LOCAL_LICENSE
    - python scripts/performance/performance.py
    - python scripts/performance/main_IJKLM.py
    - python scripts/performance/memory_check.py
  artifacts:
    name: performance_stats
    expire_in: 2 hours
    paths:
      - stats.csv
