leg-performance:
  stage: performance
  needs: []
  tags: [puma]
  image: python:3.12
  when: manual
  script:
    - python -m pip install uv && uv venv .performance_venv && source .performance_venv/bin/activate
    - uv pip install psutil
    - uv pip install .[dev,test] --force-reinstall
    - $(gamspy show base)/gamsgetkey $LOCAL_LICENSE > $(gamspy show base)/ci_license.txt
    - echo $GAMS_LICENSE > $(gamspy show base)/gamslice.txt
    - gamspy install solver mpsge scip reshop --use-uv
    - python scripts/performance/performance.py
    - python scripts/performance/read.py
    - python scripts/performance/main_IJKLM.py
    - python scripts/performance/memory_check.py
  artifacts:
    name: performance_stats
    expire_in: 2 hours
    paths:
      - stats.csv
