leg-precommit:
  stage: precommit
  when: on_success
  tags: [linux]
  image: astral/uv:python3.13-alpine
  script:
    - uv audit --frozen
    - apk add --no-cache ca-certificates git
    - uv pip install --system prek
    - prek run --all-files
