#### TESTS #####
leg-test-3.13:
  stage: test
  needs: [leg-cli-3.9]
  tags: [linux]
  image: python:3.13
  script:
    - pip install virtualenv && virtualenv venv313 && source venv313/bin/activate
    - pip install wheel build
    - python scripts/reinstall.py
    - gamspy install solver mpsge scip reshop
    - coverage run --source=gamspy -m pytest -x -v -s -m 'unit or integration or model_library' tests
    - pytest -m "doc"
    - coverage report -m --data-file=".coverage"
    - coverage xml --data-file=".coverage"
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    name: linux_3.13
    expire_in: 2 hours
    paths: [dist/*]
  coverage: '/TOTAL.*\s+(\d+\%)/'

leg-test-3.12:
  stage: test
  needs: [leg-cli-3.9]
  tags: [linux]
  image: python:3.12
  script:
    - pip install virtualenv && virtualenv venv312 && source venv312/bin/activate
    - pip install wheel build
    - python scripts/reinstall.py
    - gamspy install solver mpsge scip reshop
    - pytest -x -v -s -m 'unit or integration or model_library' tests
    - pytest -m "doc"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

leg-test-3.11:
  stage: test
  needs: [leg-cli-3.9]
  tags: [linux]
  image: python:3.11
  script:
    - pip install virtualenv && virtualenv venv311 && source venv311/bin/activate
    - pip install wheel build
    - python scripts/reinstall.py
    - gamspy install solver mpsge scip reshop
    - pytest -x -v -s -m 'unit or integration or model_library' tests
    - pytest -m "doc"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

leg-test-3.10:
  stage: test
  needs: [leg-cli-3.9]
  tags: [linux]
  image: python:3.10
  script:
    - pip install virtualenv && virtualenv venv310 && source venv310/bin/activate
    - pip install wheel build
    - python scripts/reinstall.py
    - gamspy install solver mpsge scip reshop
    - pytest -x -v -s -m 'unit or integration or model_library' tests
    - pytest -m "doc"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

leg-test-3.9:
  stage: test
  needs: [leg-cli-3.9]
  tags: [linux]
  image: python:3.9
  script:
    - pip install virtualenv && virtualenv venv39 && source venv39/bin/activate
    - pip install wheel build requests
    - python scripts/reinstall.py
    - gamspy install solver mpsge scip reshop
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.gams.com/fproske/gmswebui.git --branch gamspy --single-branch miro
    - if [ "$RUN_MIRO" == "1" ]; then cd miro && git status && ./scripts/test_gamspy_models.sh && cd ..; fi
    - pytest -x -v -s -m 'unit or integration or model_library' tests

#### ENGINE #####
leg-engine-3.13:
  stage: engine
  when: manual
  needs: []
  tags: [linux]
  image: python:3.13
  script:
    - pip install virtualenv && virtualenv venv313 && source venv313/bin/activate
    - pip install wheel build
    - python scripts/reinstall.py
    - pytest -x -v -s -m 'engine' tests

leg-engine-3.9:
  stage: engine
  when: manual
  needs: []
  tags: [linux]
  image: python:3.9
  script:
    - pip install virtualenv && virtualenv venv39 && source venv39/bin/activate
    - pip install wheel build
    - python scripts/reinstall.py
    - pytest -x -v -s -m 'engine' tests

#### NEOS #####
leg-neos-3.13:
  stage: neos
  when: manual
  needs: []
  tags: [linux]
  image: python:3.13
  script:
    - pip install virtualenv && virtualenv venv313 && source venv313/bin/activate
    - pip install wheel build
    - python scripts/reinstall.py
    - pytest -x -v -s -m 'neos' tests

leg-neos-3.9:
  stage: neos
  when: manual
  needs: []
  tags: [linux]
  image: python:3.9
  script:
    - pip install virtualenv && virtualenv venv39 && source venv39/bin/activate
    - pip install wheel build
    - python scripts/reinstall.py
    - pytest -x -v -s -m 'neos' tests
