#### TESTS #####
.lag_template:
  stage: test
  needs: [lag-cli-3.10, setup-lag-toolchain]
  tags: [linux-arm64]
  image: debian:bookworm-slim
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - apt-get update && apt-get install -y ca-certificates git
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python $PYTHON_VERSION
    - source .venv/bin/activate
    - uv sync --group test
    - uv pip install gamspy-arm-perf
    - gamspy install license $LOCAL_LICENSE
    - gamspy install solver -a --use-uv
    - gamspy uninstall solver miles --use-uv
    - python -m pytest -x -v -s -m 'unit or integration or model_library or requires_license' tests

lag-test-3.14:
  extends: .lag_template
  variables:
    PYTHON_VERSION: "3.14"
  script:
    - apt-get update && apt-get install -y ca-certificates git
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python 3.14
    - source .venv/bin/activate
    - uv sync --group test
    - uv pip install gamspy-arm-perf
    - gamspy install license $LOCAL_LICENSE
    - gamspy install solver -a --use-uv
    - gamspy uninstall solver miles --use-uv
    - COVERAGE_CORE=sysmon coverage run --source=gamspy -m pytest -x -v -s -m 'unit or integration or model_library or requires_license or doc' tests
    - coverage report -m --data-file=".coverage"
    - coverage xml --data-file=".coverage"

lag-test-3.13:
  extends: .lag_template
  variables:
    PYTHON_VERSION: "3.13"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

lag-test-3.12:
  extends: .lag_template
  variables:
    PYTHON_VERSION: "3.12"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

lag-test-3.11:
  extends: .lag_template
  variables:
    PYTHON_VERSION: "3.11"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

lag-test-3.10:
  extends: .lag_template
  variables:
    PYTHON_VERSION: "3.10"

#### ENGINE #####
.lag_engine_template:
  stage: engine
  when: manual
  needs: [setup-lag-toolchain]
  allow_failure: true
  tags: [linux-arm64]
  image: debian:bookworm-slim
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - apt-get update && apt-get install -y ca-certificates
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python $PYTHON_VERSION && source .venv/bin/activate
    - uv sync --group test
    - uv pip install gamspy-arm-perf
    - python -m pytest -x -v -s -m 'engine' tests

lag-engine-3.14:
  extends: .lag_engine_template
  variables:
    PYTHON_VERSION: "3.14"

lag-engine-3.10:
  extends: .lag_engine_template
  variables:
    PYTHON_VERSION: "3.10"

#### NEOS #####
.lag_neos_template:
  stage: neos
  when: manual
  needs: [setup-lag-toolchain]
  allow_failure: true
  tags: [linux-arm64]
  image: debian:bookworm-slim
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - apt-get update && apt-get install -y ca-certificates
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python $PYTHON_VERSION && source .venv/bin/activate
    - uv sync --group test
    - uv pip install gamspy-arm-perf
    - python -m pytest -x -v -s -m 'neos' tests

lag-neos-3.14:
  extends: .lag_neos_template
  variables:
    PYTHON_VERSION: "3.14"

lag-neos-3.10:
  extends: .lag_neos_template
  variables:
    PYTHON_VERSION: "3.10"
