#### TESTS #####
dac-test-3.13:
  stage: test
  needs: [dac-cli-3.9]
  tags: [macos-arm64]
  script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh && source $HOME/.local/bin/env
    - uv venv "gamspy-env-3.13${CI_COMMIT_SHORT_SHA}" --python 3.13
    - source "gamspy-env-3.13${CI_COMMIT_SHORT_SHA}"/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - $(gamspy show base)/gamsgetkey $LOCAL_LICENSE > $(gamspy show base)/ci_license.txt
    - gamspy install solver mpsge scip reshop --use-uv
    - COVERAGE_CORE=sysmon coverage run --source=gamspy -m pytest -x -v -s -m 'unit or integration or model_library or doc' tests
    - coverage report -m --data-file=".coverage"
    - coverage xml --data-file=".coverage"

dac-test-3.12:
  stage: test
  needs: [dac-cli-3.9]
  tags: [macos-arm64]
  script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh && source $HOME/.local/bin/env
    - uv venv "gamspy-env-3.12${CI_COMMIT_SHORT_SHA}" --python 3.12
    - source "gamspy-env-3.12${CI_COMMIT_SHORT_SHA}"/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - $(gamspy show base)/gamsgetkey $LOCAL_LICENSE > $(gamspy show base)/ci_license.txt
    - gamspy install solver mpsge scip reshop --use-uv
    - pytest -x -v -s -m 'unit or integration or model_library' tests
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

dac-test-3.11:
  stage: test
  needs: [dac-cli-3.9]
  tags: [macos-arm64]
  script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh && source $HOME/.local/bin/env
    - uv venv "gamspy-env-3.11${CI_COMMIT_SHORT_SHA}" --python 3.11
    - source "gamspy-env-3.11${CI_COMMIT_SHORT_SHA}"/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - $(gamspy show base)/gamsgetkey $LOCAL_LICENSE > $(gamspy show base)/ci_license.txt
    - gamspy install solver mpsge scip reshop --use-uv
    - pytest -x -v -s -m 'unit or integration or model_library' tests
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

dac-test-3.10:
  stage: test
  needs: [dac-cli-3.9]
  tags: [macos-arm64]
  script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh && source $HOME/.local/bin/env
    - uv venv "gamspy-env-3.10${CI_COMMIT_SHORT_SHA}" --python 3.10
    - source "gamspy-env-3.10${CI_COMMIT_SHORT_SHA}"/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - $(gamspy show base)/gamsgetkey $LOCAL_LICENSE > $(gamspy show base)/ci_license.txt
    - gamspy install solver mpsge scip reshop --use-uv
    - pytest -x -v -s -m 'unit or integration or model_library' tests
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never


dac-test-3.9:
  stage: test
  needs: [dac-cli-3.9]
  tags: [macos-arm64]
  script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh && source $HOME/.local/bin/env
    - uv venv "gamspy-env-3.9${CI_COMMIT_SHORT_SHA}" --python 3.9
    - source "gamspy-env-3.9${CI_COMMIT_SHORT_SHA}"/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - $(gamspy show base)/gamsgetkey $LOCAL_LICENSE > $(gamspy show base)/ci_license.txt
    - gamspy install solver mpsge scip reshop --use-uv
    - pytest -x -v -s -m 'unit or integration or model_library' tests
    - pytest -x -v -s -m 'doc'

#### ENGINE #####
dac-engine-3.13:
  stage: engine
  when: manual
  needs: []
  tags: [macos-arm64]
  script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh && source $HOME/.local/bin/env
    - uv venv "gamspy-env-3.13${CI_COMMIT_SHORT_SHA}" --python 3.13
    - source "gamspy-env-3.13${CI_COMMIT_SHORT_SHA}"/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - pytest -x -v -s -m 'engine' tests

dac-engine-3.9:
  stage: engine
  when: manual
  needs: []
  tags: [macos-arm64]
  script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh && source $HOME/.local/bin/env
    - uv venv "gamspy-env-3.9${CI_COMMIT_SHORT_SHA}" --python 3.9
    - source "gamspy-env-3.9${CI_COMMIT_SHORT_SHA}"/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - pytest -x -v -s -m 'engine' tests

#### NEOS #####
dac-neos-3.13:
  stage: neos
  when: manual
  needs: []
  tags: [macos-arm64]
  script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh && source $HOME/.local/bin/env
    - uv venv "gamspy-env-3.13${CI_COMMIT_SHORT_SHA}" --python 3.13
    - source "gamspy-env-3.13${CI_COMMIT_SHORT_SHA}"/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - pytest -x -v -s -m 'neos' tests

dac-neos-3.9:
  stage: neos
  when: manual
  needs: []
  tags: [macos-arm64]
  script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh && source $HOME/.local/bin/env
    - uv venv "gamspy-env-3.9${CI_COMMIT_SHORT_SHA}" --python 3.9
    - source "gamspy-env-3.9${CI_COMMIT_SHORT_SHA}"/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - pytest -x -v -s -m 'neos' tests
