#### TESTS #####
.leg_template:
  stage: test
  needs: [leg-cli-3.10, setup-leg-toolchain]
  tags: [linux]
  image: debian:bookworm-slim
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - apt-get update && apt-get install -y ca-certificates git
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python $PYTHON_VERSION && source .venv/bin/activate
    - uv sync --group test
    - gamspy install license $LOCAL_LICENSE
    - gamspy install solver -a --use-uv
    - gamspy uninstall solver miles --use-uv
    - python -m pytest -x -v -s -m 'unit or integration or model_library or requires_license' tests

leg-test-3.14:
  extends: .leg_template
  variables:
    PYTHON_VERSION: "3.14"
  script:
    - apt-get update && apt-get install -y ca-certificates git
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python 3.14 && source .venv/bin/activate
    - uv sync --group test
    - uv pip install .[torch] --force-reinstall
    - gamspy install license $LOCAL_LICENSE
    - gamspy install solver -a --use-uv
    - gamspy uninstall solver miles --use-uv
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.gams.com/miro/miro.git --branch gamspy --single-branch miro
    - if [ "$RUN_MIRO" == "1" ]; then cd miro && ./scripts/test_gamspy_models.sh && cd .. && rm -rf miro; fi
    - COVERAGE_CORE=sysmon coverage run --source=gamspy -m pytest -x -v -s -m 'unit or integration or model_library or requires_license or doc' tests
    - coverage report -m --data-file=".coverage"
    - coverage xml --data-file=".coverage"
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: '/TOTAL.*\s+(\d+\%)/'

leg-test-3.13:
  extends: .leg_template
  variables:
    PYTHON_VERSION: "3.13"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

leg-test-3.12:
  extends: .leg_template
  variables:
    PYTHON_VERSION: "3.12"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

leg-test-3.11:
  extends: .leg_template
  variables:
    PYTHON_VERSION: "3.11"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

leg-test-3.10:
  extends: .leg_template
  variables:
    PYTHON_VERSION: "3.10"

#### ENGINE #####
.leg_engine_template:
  stage: engine
  when: manual
  needs: [setup-leg-toolchain]
  allow_failure: true
  tags: [linux]
  image: debian:bookworm-slim
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - apt-get update && apt-get install -y ca-certificates
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python $PYTHON_VERSION && source .venv/bin/activate
    - uv sync --group test
    - python -m pytest -x -v -s -m 'engine' tests

leg-engine-3.14:
  extends: .leg_engine_template
  variables:
    PYTHON_VERSION: "3.14"

leg-engine-3.10:
  extends: .leg_engine_template
  variables:
    PYTHON_VERSION: "3.10"

#### NEOS #####
.leg_neos_template:
  stage: neos
  when: manual
  needs: [setup-leg-toolchain]
  allow_failure: true
  tags: [linux]
  image: debian:bookworm-slim
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - apt-get update && apt-get install -y ca-certificates
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python $PYTHON_VERSION && source .venv/bin/activate
    - uv sync --group test
    - python -m pytest -x -v -s -m 'neos' tests

leg-neos-3.14:
  extends: .leg_neos_template
  variables:
    PYTHON_VERSION: "3.14"

leg-neos-3.10:
  extends: .leg_neos_template
  variables:
    PYTHON_VERSION: "3.10"
