#### TESTS #####
.deg_template:
  stage: test
  needs: [deg-cli-3.10, setup-deg-toolchain]
  tags: [macos]
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python $PYTHON_VERSION
    - source .venv/bin/activate
    - uv sync --group test
    - $(gamspy show base)/gamsgetkey $LOCAL_LICENSE > $(gamspy show base)/ci_license.txt
    - gamspy install solver -a --use-uv
    - gamspy uninstall solver miles
    - python -B -m pytest -x -v -s -m 'unit or integration or model_library or requires_license' tests

deg-test-3.14:
  extends: .deg_template
  variables:
    PYTHON_VERSION: "3.14"
  script:
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python $PYTHON_VERSION
    - source .venv/bin/activate
    - uv sync --group test
    - $(gamspy show base)/gamsgetkey $LOCAL_LICENSE > $(gamspy show base)/ci_license.txt
    - gamspy install solver -a --use-uv
    - gamspy uninstall solver miles
    - COVERAGE_CORE=sysmon coverage run --source=gamspy -m pytest -x -v -s -m 'unit or integration or model_library or requires_license or doc' tests
    - coverage report -m --data-file=".coverage"
    - coverage xml --data-file=".coverage"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

deg-test-3.13:
  extends: .deg_template
  variables:
    PYTHON_VERSION: "3.13"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

deg-test-3.12:
  extends: .deg_template
  variables:
    PYTHON_VERSION: "3.12"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

deg-test-3.11:
  extends: .deg_template
  variables:
    PYTHON_VERSION: "3.11"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

deg-test-3.10:
  extends: .deg_template
  variables:
    PYTHON_VERSION: "3.10"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

#### ENGINE ####
.deg_engine_template:
  stage: engine
  when: manual
  needs: [setup-deg-toolchain]
  allow_failure: true
  tags: [macos]
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python $PYTHON_VERSION
    - source .venv/bin/activate
    - uv sync --group test
    - python -B -m pytest -x -v -s -m 'engine' tests

deg-engine-3.14:
  extends: .deg_engine_template
  variables:
    PYTHON_VERSION: "3.14"

deg-engine-3.10:
  extends: .deg_engine_template
  variables:
    PYTHON_VERSION: "3.10"

#### NEOS ####
.deg_neos_template:
  stage: neos
  when: manual
  needs: [setup-deg-toolchain]
  allow_failure: true
  tags: [macos]
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python $PYTHON_VERSION
    - source .venv/bin/activate
    - uv sync --group test
    - python -B -m pytest -x -v -s -m 'neos' tests

deg-neos-3.14:
  extends: .deg_neos_template
  variables:
    PYTHON_VERSION: "3.14"

deg-neos-3.10:
  extends: .deg_neos_template
  variables:
    PYTHON_VERSION: "3.10"
