#### TESTS #####
.wei_template:
  stage: test
  needs: [wei-cli-3.10, setup-wei-toolchain] 
  tags: [windows]
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - $env:Path = "$CI_PROJECT_DIR\.uv_bin;$env:Path"
    - uv venv .venv --python $env:PYTHON_VERSION
    - .venv\Scripts\Activate.ps1
    - uv sync --group test
    - gamspy install license $env:LOCAL_LICENSE
    - gamspy install solver -a --use-uv
    - gamspy uninstall solver miles --use-uv
    - python -m pytest -x -v -s -m 'unit or integration or model_library or requires_license' tests

wei-test-3.14:
  extends: .wei_template
  variables:
    PYTHON_VERSION: "3.14"
  script:
    - $env:Path = "$CI_PROJECT_DIR\.uv_bin;$env:Path"
    - uv venv .venv --python 3.14
    - .venv\Scripts\Activate.ps1
    - uv sync --group test
    - gamspy install license $env:LOCAL_LICENSE
    - gamspy install solver -a --use-uv
    - gamspy uninstall solver miles --use-uv
    - $env:COVERAGE_CORE = 'sysmon'; coverage run --source=gamspy -m pytest -x -v -s -m 'unit or integration or model_library or requires_license' tests
    - coverage report -m --data-file=".coverage"
    - coverage xml --data-file=".coverage"
    - python -m pytest -x -v -s -m 'doc'

wei-test-3.13:
  extends: .wei_template
  variables:
    PYTHON_VERSION: "3.13"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

wei-test-3.12:
  extends: .wei_template
  variables:
    PYTHON_VERSION: "3.12"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

wei-test-3.11:
  extends: .wei_template
  variables:
    PYTHON_VERSION: "3.11"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

wei-test-3.10:
  extends: .wei_template
  variables:
    PYTHON_VERSION: "3.10"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

#### ENGINE #####
.wei_engine_template:
  stage: engine
  when: manual
  needs: [setup-wei-toolchain]
  allow_failure: true
  tags: [windows]
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - $env:Path = "$CI_PROJECT_DIR\.uv_bin;$env:Path"
    - uv venv .venv --python $env:PYTHON_VERSION
    - .venv\Scripts\Activate.ps1
    - uv sync --group test
    - python -m pytest -x -v -s -m 'engine' tests

wei-engine-3.14:
  extends: .wei_engine_template
  variables:
    PYTHON_VERSION: "3.14"

wei-engine-3.10:
  extends: .wei_engine_template
  variables:
    PYTHON_VERSION: "3.10"

#### NEOS #####
.wei_neos_template:
  stage: neos
  when: manual
  needs: [setup-wei-toolchain]
  allow_failure: true
  tags: [windows]
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - $env:Path = "$CI_PROJECT_DIR\.uv_bin;$env:Path"
    - uv venv .venv --python $env:PYTHON_VERSION
    - .venv\Scripts\Activate.ps1
    - uv sync --group test
    - python -m pytest -x -v -s -m 'neos' tests

wei-neos-3.14:
  extends: .wei_neos_template
  variables:
    PYTHON_VERSION: "3.14"

wei-neos-3.10:
  extends: .wei_neos_template
  variables:
    PYTHON_VERSION: "3.10"
