#### TESTS #####
.dac_template:
  stage: test
  needs: [dac-cli-3.10, setup-dac-toolchain]
  tags: [macos-arm64]
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python $PYTHON_VERSION
    - source .venv/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - $(gamspy show base)/gamsgetkey $LOCAL_LICENSE > $(gamspy show base)/ci_license.txt
    - gamspy install solver -a --use-uv
    - gamspy uninstall solver miles
    - python -B -m pytest -x -v -s -m 'unit or integration or model_library or requires_license' tests

dac-test-3.14:
  extends: .dac_template
  variables:
    PYTHON_VERSION: "3.14"
  script:
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python 3.14
    - source .venv/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - $(gamspy show base)/gamsgetkey $LOCAL_LICENSE > $(gamspy show base)/ci_license.txt
    - gamspy install solver -a --use-uv
    - gamspy uninstall solver miles
    - COVERAGE_CORE=sysmon coverage run --source=gamspy -m pytest -x -v -s -m 'unit or integration or model_library or requires_license or doc' tests
    - coverage report -m --data-file=".coverage"
    - coverage xml --data-file=".coverage"

dac-test-3.13:
  extends: .dac_template
  variables:
    PYTHON_VERSION: "3.13"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

dac-test-3.12:
  extends: .dac_template
  variables:
    PYTHON_VERSION: "3.12"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

dac-test-3.11:
  extends: .dac_template
  variables:
    PYTHON_VERSION: "3.11"
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

dac-test-3.10:
  extends: .dac_template
  variables:
    PYTHON_VERSION: "3.10"

#### ENGINE #####
.dac_engine_template:
  stage: engine
  when: manual
  needs: [setup-dac-toolchain]
  allow_failure: true
  tags: [macos-arm64]
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python $PYTHON_VERSION
    - source .venv/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - python -B -m pytest -x -v -s -m 'engine' tests

dac-engine-3.14:
  extends: .dac_engine_template
  variables:
    PYTHON_VERSION: "3.14"

dac-engine-3.10:
  extends: .dac_engine_template
  variables:
    PYTHON_VERSION: "3.10"

#### NEOS #####
.dac_neos_template:
  stage: neos
  when: manual
  needs: [setup-dac-toolchain]
  allow_failure: true
  tags: [macos-arm64]
  variables:
    UV_PYTHON_INSTALL_DIR: "$CI_PROJECT_DIR/.uv_pythons"
  script:
    - export PATH="$CI_PROJECT_DIR/.uv_bin:$PATH"
    - uv venv .venv --python $PYTHON_VERSION
    - source .venv/bin/activate
    - uv pip install .[dev,test] pip --force-reinstall
    - python -B -m pytest -x -v -s -m 'neos' tests

dac-neos-3.14:
  extends: .dac_neos_template
  variables:
    PYTHON_VERSION: "3.14"

dac-neos-3.10:
  extends: .dac_neos_template
  variables:
    PYTHON_VERSION: "3.10"
