#### TESTS #####
lag-test-3.14:
  stage: test
  needs: [lag-cli-3.10]
  tags: [linux-arm64]
  image: python:3.14
  script:
    - python -m pip install uv && uv venv venv314 && source venv314/bin/activate
    - uv pip install .[dev,test] --force-reinstall
    - gamspy install license $LOCAL_LICENSE
    - gamspy install solver -a --use-uv
    - gamspy uninstall solver miles --use-uv
    - COVERAGE_CORE=sysmon coverage run --source=gamspy -m pytest -x -v -s -m 'unit or integration or model_library or requires_license or doc' tests
    - coverage report -m --data-file=".coverage"
    - coverage xml --data-file=".coverage"

lag-test-3.13:
  stage: test
  needs: [lag-cli-3.10]
  tags: [linux-arm64]
  image: python:3.13
  script:
    - python -m pip install uv && uv venv venv313 && source venv313/bin/activate
    - uv pip install .[dev,test] --force-reinstall
    - gamspy install license $LOCAL_LICENSE
    - gamspy install solver -a --use-uv
    - gamspy uninstall solver miles --use-uv
    - python -m pytest -x -v -s -m 'unit or integration or model_library or requires_license' tests
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

lag-test-3.12:
  stage: test
  needs: [lag-cli-3.10]
  tags: [linux-arm64]
  image: python:3.12
  script:
    - python -m pip install uv && uv venv venv312 && source venv312/bin/activate
    - uv pip install .[dev,test] --force-reinstall
    - gamspy install license $LOCAL_LICENSE
    - gamspy install solver -a --use-uv
    - gamspy uninstall solver miles --use-uv
    - python -m pytest -x -v -s -m 'unit or integration or model_library or requires_license' tests
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

lag-test-3.11:
  stage: test
  needs: [lag-cli-3.10]
  tags: [linux-arm64]
  image: python:3.11
  script:
    - python -m pip install uv && uv venv venv311 && source venv311/bin/activate
    - uv pip install .[dev,test] --force-reinstall
    - gamspy install license $LOCAL_LICENSE
    - gamspy install solver -a --use-uv
    - gamspy uninstall solver miles --use-uv
    - python -m pytest -x -v -s -m 'unit or integration or model_library or requires_license' tests
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: on_success
    - when: never

lag-test-3.10:
  stage: test
  needs: [lag-cli-3.10]
  tags: [linux-arm64]
  image: python:3.10
  script:
    - python -m pip install uv && uv venv venv310 && source venv310/bin/activate
    - uv pip install .[dev,test] --force-reinstall
    - gamspy install license $LOCAL_LICENSE
    - gamspy install solver -a --use-uv
    - gamspy uninstall solver miles --use-uv
    - python -m pytest -x -v -s -m 'unit or integration or model_library or requires_license' tests

#### ENGINE #####
lag-engine-3.14:
  stage: engine
  when: manual
  needs: []
  allow_failure: true
  tags: [linux-arm64]
  image: python:3.14
  script:
    - python -m pip install uv && uv venv venv314 && source venv314/bin/activate
    - uv pip install .[dev,test] --force-reinstall
    - python -m pytest -x -v -s -m 'engine' tests

lag-engine-3.10:
  stage: engine
  when: manual
  needs: []
  allow_failure: true
  tags: [linux-arm64]
  image: python:3.10
  script:
    - python -m pip install uv && uv venv venv310 && source venv310/bin/activate
    - uv pip install .[dev,test] --force-reinstall
    - python -m pytest -x -v -s -m 'engine' tests

#### NEOS #####
lag-neos-3.14:
  stage: neos
  when: manual
  needs: []
  allow_failure: true
  tags: [linux-arm64]
  image: python:3.14
  script:
    - python -m pip install uv && uv venv venv314 && source venv314/bin/activate
    - uv pip install .[dev,test] --force-reinstall
    - python -m pytest -x -v -s -m 'neos' tests

lag-neos-3.10:
  stage: neos
  when: manual
  needs: []
  allow_failure: true
  tags: [linux-arm64]
  image: python:3.10
  script:
    - python -m pip install uv && uv venv venv310 && source venv310/bin/activate
    - uv pip install .[dev,test] --force-reinstall
    - python -m pytest -x -v -s -m 'neos' tests
