leg-upload-wheel:
  stage: upload
  needs: []
  tags: [puma]
  image: python:3.12
  script:
    - python -m pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - python -m pip install wheel build twine pip-audit
    - pip-audit -v
    - if [ "$?" == "0" ]; then echo "Audit passed!"; else exit 1; fi
    - python -m build && twine upload dist/* -u $PF_PYPI_USERNAME -p $PF_PYPI_PASSWORD
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
      when: never
    - when: manual
