from __future__ import annotations

from typing import TYPE_CHECKING, TextIO

import gamspy._backend.backend as backend
import gamspy._miro as miro
from gamspy.exceptions import GamspyException, _customize_exception

if TYPE_CHECKING:
    from pathlib import Path

    from gamspy import Container, Model, Options


class Local(backend.Backend):
    def __init__(
        self,
        container: Container,
        options: Options,
        solver: str | None,
        solver_options: dict | Path | None,
        output: TextIO | None,
        model: Model | None,
    ) -> None:
        super().__init__(
            "local",
            container,
            options,
            solver,
            solver_options,
            output,
        )
        self.model = model

    def is_async(self):
        return False

    def run(self):
        if self.model is not None:
            self.model._assign_model_attributes()

        # Generate gams string
        gams_string = self.preprocess()

        # Run the model
        self.execute_gams(gams_string)

        # Synchronize GAMSPy with checkpoint and return a summary
        summary = self.postprocess()

        return summary

    def execute_gams(self, gams_string: str):
        try:
            self.container._execution_engine.execute(
                gams_string, self.options, self.job_name, self.model, self.output
            )

            if self.model:
                self.model._update_model_attributes()
                self.container._delete_autogenerated_symbols()
        except GamspyException as exception:
            self.container._workspace._errors.append(str(exception))
            message = _customize_exception(
                self.options,
                self.job_name,
                exception.return_code,
            )

            exception.args = (exception.message + message,)
            raise exception
        finally:
            self.container._unsaved_statements = []

    def postprocess(self):
        miro.load_miro_symbol_records(self.container)

        if self.model is not None:
            self.parse_listings(self.model)
            return self.prepare_summary(self.model)

        return None
